export enum SeatStatus {
  AVAILABLE = 'AVAILABLE',
  HELD = 'HELD',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
}

export enum CheckInStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  AWAITING_PAYMENT = 'AWAITING_PAYMENT',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum WaitlistStatus {
  WAITING = 'WAITING',
  ASSIGNED = 'ASSIGNED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum FlightStatus {
  SCHEDULED = 'SCHEDULED',
  BOARDING = 'BOARDING',
  DEPARTED = 'DEPARTED',
  CANCELLED = 'CANCELLED',
}

export enum AuditAction {
  SEAT_HELD = 'SEAT_HELD',
  SEAT_CONFIRMED = 'SEAT_CONFIRMED',
  SEAT_RELEASED = 'SEAT_RELEASED',
  SEAT_CANCELLED = 'SEAT_CANCELLED',
  WAITLIST_JOINED = 'WAITLIST_JOINED',
  WAITLIST_ASSIGNED = 'WAITLIST_ASSIGNED',
  CHECKIN_STARTED = 'CHECKIN_STARTED',
  CHECKIN_COMPLETED = 'CHECKIN_COMPLETED',
  CHECKIN_CANCELLED = 'CHECKIN_CANCELLED',
  PAYMENT_REQUESTED = 'PAYMENT_REQUESTED',
  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
  ABUSE_DETECTED = 'ABUSE_DETECTED',
}
